name:                mle-ue2
version:             0.1.0.0
github:              "Github username here/mle-ue2"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/mle-ue2#readme>

dependencies:
- base >= 4.7 && < 5
- text
- cassava
- bytestring
- vector
- split
- kdt
- random-shuffle
- MonadRandom
library:
  source-dirs: src

executables:
  mle-ue2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mle-ue2

  mle-ue2-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optc-ffast-math
      - -optc-O3
      - -O3
    dependencies:
      - mle-ue2
      - criterion
      - deepseq